name: Check Markdown style

on: [push, pull_request]

jobs:
  markdown-style:
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm install `cat npm-requirements.txt`
    - name: Run style checks
      # see: https://stackoverflow.com/a/39991116/5201771
      # alternative (probably): npx remark ...
      run: npx remark src/*.md src/*/*.md --frail --rc-path .remarkrc
