name: "schemacode_ci"

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"

jobs:
  check_skip:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.result_step.outputs.ci-skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: result_step
        uses: mstachniuk/ci-skip@master
        with:
          commit-filter: "[skip ci];[ci skip];[skip github]"
          commit-filter-separator: ";"

  latest:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    runs-on: ${{ matrix.os }}
    strategy:
        fail-fast: false
        matrix:
            os: ["ubuntu-latest"]
            python-version: ["3.8"]
    name: ${{ matrix.os }} with Python ${{ matrix.python-version }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}

      - name: "Display Python version"
        shell: bash {0}
        run: python -c "import sys; print(sys.version)"

      - name: "Install the schemacode package"
        shell: bash {0}
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install ./tools/schemacode[tests]

      - name: "Run tests"
        shell: bash {0}
        run: |
          python -m pytest --pyargs schemacode --cov=schemacode ./tools/schemacode/

      - name: "Upload coverage to CodeCov"
        uses: codecov/codecov-action@v1
        if: success()
